# Generated by Django 3.1 on 2022-06-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daybook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('point', models.IntegerField(default=5)),
            ],
        ),
    ]
