# Generated by Django 4.0.5 on 2022-07-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
